# The City in Motion — Business Analysis

## Objective

Translate the exploratory analysis into business-focused findings about
urban taxi demand, operations, trip economics, and location patterns.

## Business Questions

1. When does taxi demand peak?
2. How does demand vary by month, weekday, and hour?
3. Which pickup zones generate the most activity?
4. Which drop-off zones generate the most activity?
5. How do trip distance and duration relate to fares?
6. How does trip economics vary across time?
7. How do payment methods contribute to trip economics?
8. How do airport-originating trips differ from other trips?

In [1]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent
ANALYSIS_DIR = PROJECT_ROOT / "reports" / "analysis"

monthly_demand = pd.read_csv(ANALYSIS_DIR / "monthly_demand.csv")
hourly_demand = pd.read_csv(ANALYSIS_DIR / "hourly_demand.csv")
day_type_demand = pd.read_csv(ANALYSIS_DIR / "day_type_demand.csv")
hour_day_demand = pd.read_csv(ANALYSIS_DIR / "hour_day_demand.csv")

top_pickup_zones = pd.read_csv(ANALYSIS_DIR / "top_pickup_zones.csv")
top_dropoff_zones = pd.read_csv(ANALYSIS_DIR / "top_dropoff_zones.csv")
borough_demand = pd.read_csv(ANALYSIS_DIR / "borough_demand.csv")

monthly_economics = pd.read_csv(ANALYSIS_DIR / "monthly_economics.csv")
payment_methods = pd.read_csv(ANALYSIS_DIR / "payment_methods.csv")

distance_economics = pd.read_csv(ANALYSIS_DIR / "distance_economics.csv")
duration_economics = pd.read_csv(ANALYSIS_DIR / "duration_economics.csv")
airport_economics = pd.read_csv(ANALYSIS_DIR / "airport_vs_non_airport.csv")

print("Analysis datasets loaded successfully.")

Analysis datasets loaded successfully.

## 1. When Does Taxi Demand Peak?

### Finding

Taxi demand varies substantially across the day, with demand reaching its
highest hourly volume during the evening period.

The analysis identifies **6 PM (18:00)** as the highest-volume hour across
the 12-month study period.

The lowest hourly volume occurs at **4 AM (04:00)**.

### Operational Interpretation

The concentration of trips during the afternoon and evening suggests that
taxi activity is not evenly distributed throughout the day. Peak-period
planning should therefore account for substantially different demand levels
across operating hours.

These findings describe observed demand patterns and do not establish the
causes of those patterns.

In [2]:
peak_hour = hourly_demand.loc[
    hourly_demand["total_trips"].idxmax()
]

lowest_hour = hourly_demand.loc[
    hourly_demand["total_trips"].idxmin()
]

print(
    f"Peak hour: {int(peak_hour['pickup_hour']):02d}:00 "
    f"— {int(peak_hour['total_trips']):,} trips"
)

print(
    f"Lowest hour: {int(lowest_hour['pickup_hour']):02d}:00 "
    f"— {int(lowest_hour['total_trips']):,} trips"
)

Peak hour: 18:00 — 3,200,719 trips
Lowest hour: 04:00 — 357,240 trips

## 2. How Does Demand Vary by Month?

### Finding

Monthly taxi demand varies across the 12-month study period.

**December 2025** records the highest monthly trip volume, while **August
2025** records the lowest.

The monthly pattern indicates that demand changes over the year rather than
remaining constant.

### Key Values

- Highest: December 2025 — 4,256,070 trips
- Lowest: August 2025 — 3,312,598 trips

The analysis is descriptive and does not determine the causes of monthly
variation.

In [4]:
highest_month = monthly_demand.loc[
    monthly_demand["total_trips"].idxmax()
]

lowest_month = monthly_demand.loc[
    monthly_demand["total_trips"].idxmin()
]

highest_month_name = pd.Timestamp(
    year=int(highest_month["pickup_year"]),
    month=int(highest_month["pickup_month"]),
    day=1
).strftime("%B %Y")

lowest_month_name = pd.Timestamp(
    year=int(lowest_month["pickup_year"]),
    month=int(lowest_month["pickup_month"]),
    day=1
).strftime("%B %Y")

print(
    f"Highest-demand month: "
    f"{highest_month_name} — "
    f"{int(highest_month['total_trips']):,} trips"
)

print(
    f"Lowest-demand month: "
    f"{lowest_month_name} — "
    f"{int(lowest_month['total_trips']):,} trips"
)

Highest-demand month: December 2025 — 4,256,070 trips
Lowest-demand month: August 2025 — 3,312,598 trips

## 3. Which Pickup Zones Generate the Most Activity?

### Finding

Pickup demand is concentrated in a relatively small set of NYC taxi zones.

The highest-volume pickup zone in the 12-month dataset is **Upper East Side South**, followed by **Midtown Center**, **JFK Airport**, and **Upper East Side North**.

This indicates that pickup activity is geographically concentrated rather than evenly distributed across NYC taxi zones.

In [7]:
print(top_pickup_zones.columns.tolist())
print(top_pickup_zones.head())
top_pickup_zones.head(10)

['pickup_zone_id', 'total_trips']
   pickup_zone_id  total_trips
0             237      2059757
1             161      1900077
2             132      1852377
3             236      1825548
4             186      1416431

   pickup_zone_id  total_trips
0             237      2059757
1             161      1900077
2             132      1852377
3             236      1825548
4             186      1416431
5             162      1411489
6             230      1329862
7             142      1319262
8             170      1195953
9             234      1187192

In [9]:
top_pickup = top_pickup_zones.iloc[0]

print("Top pickup zone:")
print(top_pickup.iloc[1])

print("\nTrips:")
print(f"{int(top_pickup.iloc[-1]):,}")

print("\nTop 10 pickup zones:")
display(top_pickup_zones.head(10))

Top pickup zone:
2059757

Trips:
2,059,757

Top 10 pickup zones:

   pickup_zone_id  total_trips
0             237      2059757
1             161      1900077
2             132      1852377
3             236      1825548
4             186      1416431
5             162      1411489
6             230      1329862
7             142      1319262
8             170      1195953
9             234      1187192

## 4. Which Drop-off Zones Generate the Most Activity?

### Finding

Drop-off activity is concentrated in a number of high-volume NYC taxi zones.

The highest-volume drop-off zone in the 12-month study period is **Upper East Side North**, followed by other major Manhattan destinations.

Pickup and drop-off rankings are not identical, indicating that trip origins and destinations have different demand patterns.

In [10]:
top_dropoff = top_dropoff_zones.iloc[0]

print("Top drop-off zone:")
print(top_dropoff.iloc[1])

print("\nTrips:")
print(f"{int(top_dropoff.iloc[-1]):,}")

print("\nTop 10 drop-off zones:")
display(top_dropoff_zones.head(10))

Top drop-off zone:
1873380

Trips:
1,873,380

Top 10 drop-off zones:

   dropoff_zone_id  total_trips
0              236      1873380
1              237      1857496
2              161      1577042
3              230      1268870
4              170      1251274
5              162      1198817
6              142      1168552
7              239      1166487
8               68      1144054
9              141      1121083

## 5. How Do Trip Distance and Duration Relate to Fares?

### Finding

Trip economics vary substantially with both distance and duration.

Average fare increases across most distance bands, with longer trips associated
with higher average fares and total trip amounts.

Trip duration shows a similar broad relationship with fare, although the
shortest duration bands are not perfectly monotonic.

These are descriptive relationships in the dataset and should not be
interpreted as evidence that distance or duration alone causes the fare change.

In [11]:
print("Distance economics:")
display(distance_economics)

print("\nDuration economics:")
display(duration_economics)

Distance economics:

  distance_band  total_trips  avg_fare  avg_total_amount  avg_duration_minutes
0       <1 mile     10643654     11.81             18.83                  7.83
1     1–2 miles     13559064     13.02             20.60                 11.65
2     2–5 miles     12809196     21.08             29.16                 19.14
3    5–10 miles      5137704     34.67             45.86                 28.34
4   10–20 miles      3136438     58.76             77.13                 46.06
5     20+ miles       390824     92.36            115.37                 59.42

Duration economics:

  duration_band  total_trips  avg_distance  avg_fare  avg_total_amount
0        <5 min      4657335          1.25     11.48             18.75
1      5–10 min     10210828          2.80      9.88             16.98
2     10–20 min     16779361          4.85     17.09             24.92
3     20–30 min      7830620          8.21     28.17             37.91
4     30–45 min      3869383         13.53     42.88             56.23
5     45–60 min      1317897         16.25     58.36             75.73
6       60+ min      1011456         17.82     65.50             81.79

In [12]:
distance_highest = distance_economics.loc[
    distance_economics["avg_fare"].idxmax()
]

distance_lowest = distance_economics.loc[
    distance_economics["avg_fare"].idxmin()
]

print(
    f"Lowest average fare band: "
    f"{distance_lowest['distance_band']} — "
    f"${distance_lowest['avg_fare']:.2f}"
)

print(
    f"Highest average fare band: "
    f"{distance_highest['distance_band']} — "
    f"${distance_highest['avg_fare']:.2f}"
)

Lowest average fare band: <1 mile — $11.81
Highest average fare band: 20+ miles — $92.36

In [13]:
duration_highest = duration_economics.loc[
    duration_economics["avg_fare"].idxmax()
]

duration_lowest = duration_economics.loc[
    duration_economics["avg_fare"].idxmin()
]

print(
    f"Lowest average fare duration band: "
    f"{duration_lowest['duration_band']} — "
    f"${duration_lowest['avg_fare']:.2f}"
)

print(
    f"Highest average fare duration band: "
    f"{duration_highest['duration_band']} — "
    f"${duration_highest['avg_fare']:.2f}"
)

Lowest average fare duration band: 5–10 min — $9.88
Highest average fare duration band: 60+ min — $65.50

## 6. How Does Trip Economics Vary Across Months?

### Finding

Monthly trip volume and trip economics do not move identically across the
study period.

December 2025 records the highest total trip amount, while August 2025 records
the lowest. Average trip amounts also vary between months, indicating that
changes in total trip value are influenced by both trip volume and the average
value of individual trips.

These results are descriptive and do not establish the causes of monthly
variation.

In [14]:
print("Monthly trip economics:")
display(monthly_economics)

Monthly trip economics:

,pickup_year,pickup_month,total_trips,total_fare,total_tips,total_amount,avg_fare,avg_total_amount
0,2025,8,3312598,67351546.00,9712402.48,9.604229e+07,20.33,28.99
1,2025,9,3997883,84409585.85,12149928.16,1.194535e+08,21.11,29.88
2,2025,10,4106958,83630631.30,13247017.67,1.208492e+08,20.36,29.43
3,2025,11,3784463,74221300.01,11965132.92,1.078570e+08,19.61,28.50
4,2025,12,4256070,96873272.25,12175880.44,1.344583e+08,22.76,31.59
5,2026,1,3684859,78458716.13,9715683.41,1.098964e+08,21.29,29.82
6,2026,2,3372528,74230519.34,8973117.28,1.031805e+08,22.01,30.59
7,2026,3,3931096,84761501.87,11294695.38,1.195527e+08,21.56,30.41
8,2026,4,3816348,81108093.50,11471837.24,1.153580e+08,21.25,30.23
9,2026,5,4075904,88333579.49,12177550.60,1.251243e+08,21.67,30.70
10,2026,6,3822877,82595743.97,11462289.34,1.175069e+08,21.61,30.74
11,2026,7,3515296,74824825.50,9861105.07,1.064886e+08,21.29,30.29

In [15]:
highest_total = monthly_economics.loc[
    monthly_economics["total_amount"].idxmax()
]

lowest_total = monthly_economics.loc[
    monthly_economics["total_amount"].idxmin()
]

print(
    f"Highest total trip amount: "
    f"{int(highest_total['pickup_year'])}-"
    f"{int(highest_total['pickup_month']):02d} — "
    f"${highest_total['total_amount']:,.2f}"
)

print(
    f"Lowest total trip amount: "
    f"{int(lowest_total['pickup_year'])}-"
    f"{int(lowest_total['pickup_month']):02d} — "
    f"${lowest_total['total_amount']:,.2f}"
)

Highest total trip amount: 2025-12 — $134,458,304.08
Lowest total trip amount: 2025-08 — $96,042,288.49

In [16]:
highest_avg = monthly_economics.loc[
    monthly_economics["avg_total_amount"].idxmax()
]

lowest_avg = monthly_economics.loc[
    monthly_economics["avg_total_amount"].idxmin()
]

print(
    f"Highest average trip amount: "
    f"{int(highest_avg['pickup_year'])}-"
    f"{int(highest_avg['pickup_month']):02d} — "
    f"${highest_avg['avg_total_amount']:.2f}"
)

print(
    f"Lowest average trip amount: "
    f"{int(lowest_avg['pickup_year'])}-"
    f"{int(lowest_avg['pickup_month']):02d} — "
    f"${lowest_avg['avg_total_amount']:.2f}"
)

Highest average trip amount: 2025-12 — $31.59
Lowest average trip amount: 2025-11 — $28.50

## 7. How Do Payment Methods Contribute to Trip Economics?

### Finding

Payment-type codes are unevenly distributed across the dataset. Payment type
code 1 represents the largest share of recorded trips, followed by codes 0
and 2.

The analysis also shows differences in average trip amount and average tip
across payment-type codes.

Because the TLC dataset stores payment methods as numeric codes, the codes
should be mapped to their official TLC definitions before presenting named
payment methods in the final dashboard.

This analysis describes the recorded payment-type distribution and does not
establish why the observed differences occur.

In [17]:
print("Payment method analysis:")
display(payment_methods)

Payment method analysis:

   payment_type  total_trips  trip_percentage  avg_total_amount  avg_tip
0             1     29985561            65.65             30.57     4.33
1             0     10990659            24.06             30.58     0.41
2             2      4184163             9.16             25.95     0.00
3             4       360831             0.79             29.61     0.01
4             3       155664             0.34             23.37     0.00
5             5            2             0.00              0.00     0.00

In [18]:
largest_payment_type = payment_methods.loc[
    payment_methods["total_trips"].idxmax()
]

print(
    f"Largest payment-type code: "
    f"{int(largest_payment_type['payment_type'])}"
)

print(
    f"Trips: {int(largest_payment_type['total_trips']):,}"
)

print(
    f"Trip share: {largest_payment_type['trip_percentage']:.2f}%"
)

Largest payment-type code: 1
Trips: 29,985,561
Trip share: 65.65%

## 8. How Do Airport-Originating Trips Differ From Other Trips?

### Finding

Airport-originating trips account for a smaller share of total trips but have
substantially different trip characteristics from non-airport trips.

Airport-originating trips have higher average distance, duration, fare, and
total trip amount than non-airport trips.

Airport trips are defined here as trips whose pickup location is JFK Airport
or LaGuardia Airport. Therefore, this comparison concerns airport-originating
trips only and does not represent every trip involving an airport.

The results are descriptive and do not establish the causes of these
differences.

In [19]:
print("Airport vs non-airport analysis:")
display(airport_economics)

Airport vs non-airport analysis:

,trip_type,total_trips,avg_distance,avg_duration_minutes,avg_fare,avg_total_amount
0,Airport,3037690,12.83,37.40,55.94,76.75
1,Non-Airport,42639190,5.46,16.09,18.78,26.80

In [20]:
airport_trips = airport_economics.loc[
    airport_economics["trip_type"] == "Airport",
    "total_trips"
].iloc[0]

total_trips = airport_economics["total_trips"].sum()

airport_share = airport_trips / total_trips * 100

print(f"Airport-originating trips: {airport_trips:,}")
print(f"Airport trip share: {airport_share:.2f}%")

Airport-originating trips: 3,037,690
Airport trip share: 6.65%